export { default as Main } from './Main'
export { default as Post } from './Post'
export { default as Header } from './Header'
export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as Comment } from './Comment'